---

kind: pipeline
type: docker
name: daily updates pipeline

clone:
  depth: 1

steps:
  - name: Update plex server(s)
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      SUPER_USER:
          from_secret: super_user
      SUPER_PASS:
        from_secret: super_pass
    settings:
      galaxy: .ansible/roles/requirements.update.yaml
      playbook: .ansible/update.yaml
      inventory: .ansible/inventory/production
      private_key:
        from_secret: ansible_private_key
      vault_password:
        from_secret: ansible_vault_password

trigger:
  event:
    - cron
  cron:
    - daily-updates
...
