---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy plex media server
    image: docker.nexus.diesel.net/drone-ansible:7.2.0
    environment:
      PLEX_CLAIM_TOKEN:
        from_secret: plex_claim_token
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/prod.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa

trigger:
  event:
    - push
  branch:
    - development
    - stable

...
