---
kind: pipeline
type: docker
name: deploy (development)

steps:
  - name: deploy plex media server
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      PLEX_CLAIM_TOKEN:
        from_secret: plex_claim_token
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/development
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  event:
    - push
  branch:
    - development

# ---
# kind: pipeline
# type: docker
# name: deploy

#   steps:
#     - name: deploy plex media server
#       image: plugins/ansible:3
#       environment:
#         ANSIBLE_CONFIG: .ansible/ansible.cfg
#         PLEX_CLAIM_TOKEN:
#           from_secret: plex_claim_token
#       settings:
#         galaxy: .ansible/roles/requirements.yaml
#         inventory: .ansible/inventories/production
#         playbook: .ansible/deploy.yaml
#         private_key:
#           from_secret: automation_id_rsa
#         vault_password:
#           from_secret: ansible_vault_password

# trigger:
#   event:
#     - push
#   branch:
#     - stable
# ...
