---
kind: pipeline
type: docker
name: deploy (development)

steps:
  - name: deploy plex media server
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      CLAIM_TOKEN:
        from_secret: claim_token
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/development
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  event:
    - push
  branch:
    - development

---
kind: pipeline
type: docker
name: deploy (production)

steps:
  - name: deploy plex media server
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/production
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
      extra_vars: version=production

trigger:
  event:
    - push
  branch:
    - stable
...
