version: '3.8'
services: 

  media-server:
    image: plexinc/pms-docker:public
    hostname: {{ plex_host }}
    environment:
      - PLEX_UID={{ plex_user_id }}
      - PLEX_GID={{ plex_group_id }}
      - TZ={{ local_timezone }}
      - PLEX_CLAIM={{ plex_claim_token }}
      - ADVERTISE_IP=http://{{ ansible_default_ipv4['address'] }}:{{ plex_web_port }}/
      - NVIDIA_DRIVER_CAPABILITIES=video,utility
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - {{ config_dir }}:/transcode # transient
      - {{ data_dir }}:/config:rw
      - plex-media:/data:ro
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.{{ app_name }}-{{ version }}.loadbalancer.server.port=32400
        - traefik.http.routers.{{ app_name }}-{{ version }}.rule=Host(`{{ proxy_hostname }}`)
        - traefik.http.routers.{{ app_name }}-{{ version }}.tls.certresolver=cloudflare
        - traefik.http.routers.{{ app_name }}-{{ version }}.tls.domains[0].main={{ proxy_cert_main }}
        - traefik.http.routers.{{ app_name }}-{{ version }}.tls.domains[0].sans={{ proxy_cert_sans }}
        - traefik.http.routers.{{ app_name }}-{{ version }}.service={{ app_name }}-{{ version }}
    networks:
      - host-net
      - traefik-net

volumes:

  plex-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr={{ nfs_host }},ro,nfsvers=4,async
      device: :{{ nfs_media_path }}

networks:
  host-net:
    external: true
    name: host
  traefik-net:
    external: true
    name: '{{ traefik_network }}'
