- hosts: swarm_manager
  roles:
    - application

  tasks:

    - include_role:
        name: application
        tasks_from: make_config_dir

    - include_role:
        name: application
        tasks_from: make_data_dir

    - name: Ensure {{ data_dir }}/persistent exists
      file:
        state: directory
        path: '{{ data_dir }}/persistent'

    - name: Ensure {{ data_dir }}/transient exists
      file:
        state: directory
        path: '{{ data_dir }}/transient'
    
    - name: allow ports through firewall on host
      ufw:
        rule: allow
        port: "{{ item['port'] }}"
        proto: "{{ item['proto'] }}"
      become: yes
      loop: "{{ plex_ports }}"
      loop_control:
        loop_var: item

    - name: reload firewall and enable at boot
      ufw:
        state: enabled
        policy: deny
      become: yes

    - include_role:
        name: docker
        tasks_from: stack_deploy
